# Generated by Django 4.1.7 on 2023-04-06 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0019_roles_teacher_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('reason', models.CharField(max_length=300)),
                ('guardian_phone', models.CharField(max_length=11)),
                ('relation', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('cc', models.CharField(max_length=100, null=True)),
                ('hod', models.CharField(max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
    ]
