# Generated by Django 4.1.7 on 2023-04-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='max_marks',
            field=models.DecimalField(decimal_places=1, default=25, max_digits=3),
        ),
    ]
