# Generated by Django 4.1.7 on 2023-04-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_rename_sem1_univ_result_sem01_and_more'),
        ('marks', '0005_alter_univ_result_univ_roll_no'),
    ]

    operations = [
    ]
