# Generated by Django 4.1.7 on 2023-04-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='curent_sem',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth')], default=1),
        ),
        migrations.AlterField(
            model_name='agg_attendance',
            name='status',
            field=models.CharField(choices=[('1', 'Present'), ('0', 'Absent')], max_length=1),
        ),
    ]
