# Generated by Django 4.1.7 on 2023-04-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_student_otp_alter_teacher_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
