# Generated by Django 4.1.7 on 2023-04-04 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_teacher_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name='agg_attendance',
            name='status',
            field=models.CharField(choices=[('P', 'P'), ('A', 'A')], default='A', max_length=1),
        ),
        migrations.CreateModel(
            name='total_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_classes', models.IntegerField(default=0)),
                ('session', models.CharField(max_length=4)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.subject')),
            ],
        ),
    ]
