# Generated by Django 4.1.7 on 2023-04-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_student_section_student_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agg_attendance',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
