# Generated by Django 4.1.7 on 2023-04-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_agg_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
