# Generated by Django 4.1.7 on 2023-04-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_alter_agg_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_attendance',
            name='date',
        ),
    ]
