# Generated by Django 4.1.7 on 2023-04-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_remove_agg_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_attendance',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1),
        ),
    ]
