# Generated by Django 4.1.7 on 2023-04-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_agg_attendance_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='univ_roll_no',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.CharField(max_length=60),
        ),
    ]
