# Generated by Django 4.1.7 on 2023-04-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_student_univ_roll_no_alter_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='univ_roll_no',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
