# Generated by Django 4.1.7 on 2023-04-06 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_student_univ_roll_no_alter_student_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Teacher', 'Teacher'), ('HOD', 'HOD'), ('Principal', 'Principal'), ('CC', 'Class Coordinator')], default='Teacher', max_length=100)),
                ('semester', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth')], default=None)),
                ('department', models.CharField(choices=[('BBA', 'BBA'), ('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics and Communication Engineering')], default=None, max_length=3)),
                ('section', models.CharField(choices=[('All', 'All'), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='All', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='attendance.roles'),
        ),
    ]
