# Generated by Django 4.1.7 on 2023-04-06 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_roles_teacher_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='attendance.teacher'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='department',
            field=models.CharField(choices=[('BBA', 'BBA'), ('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics and Communication Engineering')], default='All', max_length=3),
        ),
        migrations.AlterField(
            model_name='roles',
            name='semester',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth')], default='All'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='Teacher', max_length=150),
        ),
    ]
