# Generated by Django 4.1.7 on 2023-04-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_roles_teacher_alter_roles_department_and_more'),
        ('attendance', '0021_alter_student_univ_roll_no'),
    ]

    operations = [
    ]
