# Generated by Django 4.1.7 on 2023-04-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_merge_20230406_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='univ_roll_no',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
