# Generated by Django 4.1.7 on 2023-04-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_alter_student_univ_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('HOD', 'HOD'), ('Principal', 'Principal'), ('CC', 'Class Coordinator')], default='Teacher', max_length=150),
        ),
    ]
