# Generated by Django 4.1.7 on 2023-04-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_alter_teacher_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='Teacher', max_length=150),
        ),
    ]
